// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLYuCk00yTT-cfNAY0FFvEpWxrez5RRU',
    appId: '1:584174165103:web:cc86b0a9cf04616f27819a',
    messagingSenderId: '584174165103',
    projectId: 'test-project-1-8ca8f',
    authDomain: 'test-project-1-8ca8f.firebaseapp.com',
    storageBucket: 'test-project-1-8ca8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQEybDO7BOS-O_fU-8Qgdc3nLegDfO5M',
    appId: '1:584174165103:android:d4c12bb821c3cbd327819a',
    messagingSenderId: '584174165103',
    projectId: 'test-project-1-8ca8f',
    storageBucket: 'test-project-1-8ca8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-0HgwCdCD0UhjXm0_qUNTGRvCS67Vio',
    appId: '1:584174165103:ios:d4647f4b189cb44f27819a',
    messagingSenderId: '584174165103',
    projectId: 'test-project-1-8ca8f',
    storageBucket: 'test-project-1-8ca8f.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );
}
